[package]
name = "part-two"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.17.0", features = ["train", "ndarray"] }
burn-ndarray = { version = "0.17.0", package = "burn-ndarray" }
env_logger = "0.11.8"
rand = "0.9.1"
